//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Booking_id { get; set; }
        public int Hotel_No { get; set; }
        public int Guest_No { get; set; }
        public System.DateTime Date_From { get; set; }
        public System.DateTime Date_To { get; set; }
        public int Room_No { get; set; }
    
        public virtual Room Room { get; set; }
        public virtual Guest Guest { get; set; }
    }
}
